// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5d5uozwa-G6JoiTpHdknOpIuTOp6vDM',
    appId: '1:377531536938:web:8b3ef331e217f9ccc91553',
    messagingSenderId: '377531536938',
    projectId: 'fyp1-af990',
    authDomain: 'fyp1-af990.firebaseapp.com',
    storageBucket: 'fyp1-af990.appspot.com',
    measurementId: 'G-9VL2282JNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFaJRpzUIA2SNzWxu8PKDsNX1hEi6p20',
    appId: '1:377531536938:android:80c49a83acfd0d5dc91553',
    messagingSenderId: '377531536938',
    projectId: 'fyp1-af990',
    storageBucket: 'fyp1-af990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYEFfbZwwoK752nT9kOHg_0_Gcxq63keE',
    appId: '1:377531536938:ios:36f81cf5bd240ae7c91553',
    messagingSenderId: '377531536938',
    projectId: 'fyp1-af990',
    storageBucket: 'fyp1-af990.appspot.com',
    iosBundleId: 'com.geareab.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYEFfbZwwoK752nT9kOHg_0_Gcxq63keE',
    appId: '1:377531536938:ios:d2c1fc49c19ba3cfc91553',
    messagingSenderId: '377531536938',
    projectId: 'fyp1-af990',
    storageBucket: 'fyp1-af990.appspot.com',
    iosBundleId: 'com.example.fypApp',
  );
}
